### ISSUE TITLE
Implement offline token validation helper

### ISSUE THREAD

**Issue by emgrav** [famedly/zitadel-rust-client#35]
### Steps to implement
* Implement helper function to perform offline Zitadel access token validation

### Input
* Zitadel private key JWT access token

### Output
TBD, depends on https://github.com/famedly/vzd-fhir-directory-proxy/issues/88

https://zitadel.com/docs/guides/integrate/token-introspection/private-key-jwt
https://zitadel.com/docs/guides/integrate/service-users/private-key-jwt

**Comment by mzaniolo** [comment]
On vzd-fhir-directory-proxy we decided to don't do introspection but rather use a JWT and validate the signature. We won't need the introspection helper anymore but it would be good to have a helper to get the public keys from Zitadel. We could even have the helper to return only the key we are interested in.

[Zitadel docs](https://zitadel.com/docs/guides/integrate/login/oidc/webkeys#json-web-key-set)
